<?php

namespace Database\Seeders\Localisation;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Shared\Localisation\Country;

class CountryTableSeeders extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countriesData = [
            ['id' => '1', 'country' => 'afghanistan'],
            ['id' => '2', 'country' => 'albania'],
            ['id' => '3', 'country' => 'algeria'],
            ['id' => '4', 'country' => 'american samoa'],
            ['id' => '5', 'country' => 'andorra'],
            ['id' => '6', 'country' => 'angola'],
            ['id' => '7', 'country' => 'anguilla'],
            ['id' => '8', 'country' => 'antarctica'],
            ['id' => '9', 'country' => 'antigua and barbuda'],
            ['id' => '10', 'country' => 'argentina'],
            ['id' => '11', 'country' => 'armenia'],
            ['id' => '12', 'country' => 'aruba'],
            ['id' => '13', 'country' => 'australia'],
            ['id' => '14', 'country' => 'austria'],
            ['id' => '15', 'country' => 'azerbaijan'],
            ['id' => '16', 'country' => 'bahamas the'],
            ['id' => '17', 'country' => 'bahrain'],
            ['id' => '18', 'country' => 'bangladesh'],
            ['id' => '19', 'country' => 'barbados'],
            ['id' => '20', 'country' => 'belarus'],
            ['id' => '21', 'country' => 'belgium'],
            ['id' => '22', 'country' => 'belize'],
            ['id' => '23', 'country' => 'benin'],
            ['id' => '24', 'country' => 'bermuda'],
            ['id' => '25', 'country' => 'bhutan'],
            ['id' => '26', 'country' => 'bolivia'],
            ['id' => '27', 'country' => 'bosnia and herzegovina'],
            ['id' => '28', 'country' => 'botswana'],
            ['id' => '29', 'country' => 'bouvet island'],
            ['id' => '30', 'country' => 'brazil'],
            ['id' => '31', 'country' => 'british indian ocean territory'],
            ['id' => '32', 'country' => 'brunei'],
            ['id' => '33', 'country' => 'bulgaria'],
            ['id' => '34', 'country' => 'burkina faso'],
            ['id' => '35', 'country' => 'burundi'],
            ['id' => '36', 'country' => 'cambodia'],
            ['id' => '37', 'country' => 'cameroon'],
            ['id' => '38', 'country' => 'canada'],
            ['id' => '39', 'country' => 'cape verde'],
            ['id' => '40', 'country' => 'cayman islands'],
            ['id' => '41', 'country' => 'central african republic'],
            ['id' => '42', 'country' => 'chad'],
            ['id' => '43', 'country' => 'chile'],
            ['id' => '44', 'country' => 'china'],
            ['id' => '45', 'country' => 'christmas island'],
            ['id' => '46', 'country' => 'cocos (keeling) islands'],
            ['id' => '47', 'country' => 'colombia'],
            ['id' => '48', 'country' => 'comoros'],
            ['id' => '49', 'country' => 'congo'],
            ['id' => '50', 'country' => 'congo the democratic republic of the'],
            ['id' => '51', 'country' => 'cook islands'],
            ['id' => '52', 'country' => 'costa rica'],
            ['id' => '53', 'country' => 'cote d\'ivoire (ivory coast)'],
            ['id' => '54', 'country' => 'croatia (hrvatska)'],
            ['id' => '55', 'country' => 'cuba'],
            ['id' => '56', 'country' => 'cyprus'],
            ['id' => '57', 'country' => 'czech republic'],
            ['id' => '58', 'country' => 'denmark'],
            ['id' => '59', 'country' => 'djibouti'],
            ['id' => '60', 'country' => 'dominica'],
            ['id' => '61', 'country' => 'dominican republic'],
            ['id' => '62', 'country' => 'east timor'],
            ['id' => '63', 'country' => 'ecuador'],
            ['id' => '64', 'country' => 'egypt'],
            ['id' => '65', 'country' => 'el salvador'],
            ['id' => '66', 'country' => 'equatorial guinea'],
            ['id' => '67', 'country' => 'eritrea'],
            ['id' => '68', 'country' => 'estonia'],
            ['id' => '69', 'country' => 'ethiopia'],
            ['id' => '70', 'country' => 'external territories of australia'],
            ['id' => '71', 'country' => 'falkland islands'],
            ['id' => '72', 'country' => 'faroe islands'],
            ['id' => '73', 'country' => 'fiji islands'],
            ['id' => '74', 'country' => 'finland'],
            ['id' => '75', 'country' => 'france'],
            ['id' => '76', 'country' => 'french guiana'],
            ['id' => '77', 'country' => 'french polynesia'],
            ['id' => '78', 'country' => 'french southern territories'],
            ['id' => '79', 'country' => 'gabon'],
            ['id' => '80', 'country' => 'gambia the'],
            ['id' => '81', 'country' => 'georgia'],
            ['id' => '82', 'country' => 'germany'],
            ['id' => '83', 'country' => 'ghana'],
            ['id' => '84', 'country' => 'gibraltar'],
            ['id' => '85', 'country' => 'greece'],
            ['id' => '86', 'country' => 'greenland'],
            ['id' => '87', 'country' => 'grenada'],
            ['id' => '88', 'country' => 'guadeloupe'],
            ['id' => '89', 'country' => 'guam'],
            ['id' => '90', 'country' => 'guatemala'],
            ['id' => '91', 'country' => 'guernsey and alderney'],
            ['id' => '92', 'country' => 'guinea'],
            ['id' => '93', 'country' => 'guinea-bissau'],
            ['id' => '94', 'country' => 'guyana'],
            ['id' => '95', 'country' => 'haiti'],
            ['id' => '96', 'country' => 'heard and mcdonald islands'],
            ['id' => '97', 'country' => 'honduras'],
            ['id' => '98', 'country' => 'hong kong s.a.r.'],
            ['id' => '99', 'country' => 'hungary'],
            ['id' => '100', 'country' => 'iceland'],
            ['id' => '101', 'country' => 'india'],
            ['id' => '102', 'country' => 'indonesia'],
            ['id' => '103', 'country' => 'iran'],
            ['id' => '104', 'country' => 'iraq'],
            ['id' => '105', 'country' => 'ireland'],
            ['id' => '106', 'country' => 'israel'],
            ['id' => '107', 'country' => 'italy'],
            ['id' => '108', 'country' => 'jamaica'],
            ['id' => '109', 'country' => 'japan'],
            ['id' => '110', 'country' => 'jersey'],
            ['id' => '111', 'country' => 'jordan'],
            ['id' => '112', 'country' => 'kazakhstan'],
            ['id' => '113', 'country' => 'kenya'],
            ['id' => '114', 'country' => 'kiribati'],
            ['id' => '115', 'country' => 'korea north'],
            ['id' => '116', 'country' => 'korea south'],
            ['id' => '117', 'country' => 'kuwait'],
            ['id' => '118', 'country' => 'kyrgyzstan'],
            ['id' => '119', 'country' => 'laos'],
            ['id' => '120', 'country' => 'latvia'],
            ['id' => '121', 'country' => 'lebanon'],
            ['id' => '122', 'country' => 'lesotho'],
            ['id' => '123', 'country' => 'liberia'],
            ['id' => '124', 'country' => 'libya'],
            ['id' => '125', 'country' => 'liechtenstein'],
            ['id' => '126', 'country' => 'lithuania'],
            ['id' => '127', 'country' => 'luxembourg'],
            ['id' => '128', 'country' => 'macau s.a.r.'],
            ['id' => '129', 'country' => 'macedonia'],
            ['id' => '130', 'country' => 'madagascar'],
            ['id' => '131', 'country' => 'malawi'],
            ['id' => '132', 'country' => 'malaysia'],
            ['id' => '133', 'country' => 'maldives'],
            ['id' => '134', 'country' => 'mali'],
            ['id' => '135', 'country' => 'malta'],
            ['id' => '136', 'country' => 'man (isle of)'],
            ['id' => '137', 'country' => 'marshall islands'],
            ['id' => '138', 'country' => 'martinique'],
            ['id' => '139', 'country' => 'mauritania'],
            ['id' => '140', 'country' => 'mauritius'],
            ['id' => '141', 'country' => 'mayotte'],
            ['id' => '142', 'country' => 'mexico'],
            ['id' => '143', 'country' => 'micronesia'],
            ['id' => '144', 'country' => 'moldova'],
            ['id' => '145', 'country' => 'monaco'],
            ['id' => '146', 'country' => 'mongolia'],
            ['id' => '147', 'country' => 'montserrat'],
            ['id' => '148', 'country' => 'morocco'],
            ['id' => '149', 'country' => 'mozambique'],
            ['id' => '150', 'country' => 'myanmar'],
            ['id' => '151', 'country' => 'namibia'],
            ['id' => '152', 'country' => 'nauru'],
            ['id' => '153', 'country' => 'nepal'],
            ['id' => '154', 'country' => 'netherlands antilles'],
            ['id' => '155', 'country' => 'netherlands the'],
            ['id' => '156', 'country' => 'new caledonia'],
            ['id' => '157', 'country' => 'new zealand'],
            ['id' => '158', 'country' => 'nicaragua'],
            ['id' => '159', 'country' => 'niger'],
            ['id' => '160', 'country' => 'nigeria'],
            ['id' => '161', 'country' => 'niue'],
            ['id' => '162', 'country' => 'norfolk island'],
            ['id' => '163', 'country' => 'northern mariana islands'],
            ['id' => '164', 'country' => 'norway'],
            ['id' => '165', 'country' => 'oman'],
            ['id' => '166', 'country' => 'pakistan'],
            ['id' => '167', 'country' => 'palau'],
            ['id' => '168', 'country' => 'palestinian territory occupied'],
            ['id' => '169', 'country' => 'panama'],
            ['id' => '170', 'country' => 'papua new guinea'],
            ['id' => '171', 'country' => 'paraguay'],
            ['id' => '172', 'country' => 'peru'],
            ['id' => '173', 'country' => 'philippines'],
            ['id' => '174', 'country' => 'pitcairn island'],
            ['id' => '175', 'country' => 'poland'],
            ['id' => '176', 'country' => 'portugal'],
            ['id' => '177', 'country' => 'puerto rico'],
            ['id' => '178', 'country' => 'qatar'],
            ['id' => '179', 'country' => 'reunion'],
            ['id' => '180', 'country' => 'romania'],
            ['id' => '181', 'country' => 'russia'],
            ['id' => '182', 'country' => 'rwanda'],
            ['id' => '183', 'country' => 'saint helena'],
            ['id' => '184', 'country' => 'saint kitts and nevis'],
            ['id' => '185', 'country' => 'saint lucia'],
            ['id' => '186', 'country' => 'saint pierre and miquelon'],
            ['id' => '187', 'country' => 'saint vincent and the grenadines'],
            ['id' => '188', 'country' => 'samoa'],
            ['id' => '189', 'country' => 'san marino'],
            ['id' => '190', 'country' => 'sao tome and principe'],
            ['id' => '191', 'country' => 'saudi arabia'],
            ['id' => '192', 'country' => 'senegal'],
            ['id' => '193', 'country' => 'serbia'],
            ['id' => '194', 'country' => 'seychelles'],
            ['id' => '195', 'country' => 'sierra leone'],
            ['id' => '196', 'country' => 'singapore'],
            ['id' => '197', 'country' => 'slovakia'],
            ['id' => '198', 'country' => 'slovenia'],
            ['id' => '199', 'country' => 'smaller territories of the uk'],
            ['id' => '200', 'country' => 'solomon islands'],
            ['id' => '201', 'country' => 'somalia'],
            ['id' => '202', 'country' => 'south africa'],
            ['id' => '203', 'country' => 'south georgia'],
            ['id' => '204', 'country' => 'south sudan'],
            ['id' => '205', 'country' => 'spain'],
            ['id' => '206', 'country' => 'sri lanka'],
            ['id' => '207', 'country' => 'sudan'],
            ['id' => '208', 'country' => 'suricountry'],
            ['id' => '209', 'country' => 'svalbard and jan mayen islands'],
            ['id' => '210', 'country' => 'swaziland'],
            ['id' => '211', 'country' => 'sweden'],
            ['id' => '212', 'country' => 'switzerland'],
            ['id' => '213', 'country' => 'syria'],
            ['id' => '214', 'country' => 'taiwan'],
            ['id' => '215', 'country' => 'tajikistan'],
            ['id' => '216', 'country' => 'tanzania'],
            ['id' => '217', 'country' => 'thailand'],
            ['id' => '218', 'country' => 'togo'],
            ['id' => '219', 'country' => 'tokelau'],
            ['id' => '220', 'country' => 'tonga'],
            ['id' => '221', 'country' => 'trinidad and tobago'],
            ['id' => '222', 'country' => 'tunisia'],
            ['id' => '223', 'country' => 'turkey'],
            ['id' => '224', 'country' => 'turkmenistan'],
            ['id' => '225', 'country' => 'turks and caicos islands'],
            ['id' => '226', 'country' => 'tuvalu'],
            ['id' => '227', 'country' => 'uganda'],
            ['id' => '228', 'country' => 'ukraine'],
            ['id' => '229', 'country' => 'united arab emirates'],
            ['id' => '230', 'country' => 'united kingdom'],
            ['id' => '231', 'country' => 'united states'],
            ['id' => '232', 'country' => 'united states minor outlying islands'],
            ['id' => '233', 'country' => 'uruguay'],
            ['id' => '234', 'country' => 'uzbekistan'],
            ['id' => '235', 'country' => 'vanuatu'],
            ['id' => '236', 'country' => 'vatican city state (holy see)'],
            ['id' => '237', 'country' => 'venezuela'],
            ['id' => '238', 'country' => 'vietnam'],
            ['id' => '239', 'country' => 'virgin islands (british)'],
            ['id' => '240', 'country' => 'virgin islands (us)'],
            ['id' => '241', 'country' => 'wallis and futuna islands'],
            ['id' => '242', 'country' => 'western sahara'],
            ['id' => '243', 'country' => 'yemen'],
            ['id' => '244', 'country' => 'yugoslavia'],
            ['id' => '245', 'country' => 'zambia'],
            ['id' => '246', 'country' => 'zimbabwe']
        ];

        foreach ($countriesData as $countryData) {
            Country::create([
                'id' => $countryData['id'],
                'country' => $countryData['country'],
            ]);
        }
    }
}
